with raw_csv as (

    select * 
    from read_csv(
        'raw_data/edubase_all_fields.csv',
        header = true,
        escape = '"',
        strict_mode = false,
        all_varchar = true, -- read all values as varchar to avoid type conversion errors, convert later
        nullstr = 'null'    -- 'null' strings in csvs converted to SQL NULL values
    )

),

stg_gias as (

    select
         -- integers
        try_cast(URN as integer) as urn,
        try_cast(LAcode as integer) as la_code,
        try_cast(EstablishmentNumber as integer) as establishment_number,
        try_cast(TypeOfEstablishmentcode as integer) as type_of_establishment_code,
        try_cast(EstablishmentTypeGroupcode as integer) as establishment_type_group_code,
        try_cast(EstablishmentStatuscode as integer) as establishment_status_code,
        try_cast(ReasonEstablishmentOpenedcode as integer) as reason_establishment_opened_code,
        try_cast(ReasonEstablishmentClosedcode as integer) as reason_establishment_closed_code,
        try_cast(PhaseOfEducationcode as integer) as phase_of_education_code,
        try_cast(StatutoryLowAge as integer) as statutory_low_age,
        try_cast(StatutoryHighAge as integer) as statutory_high_age,
        try_cast(Boarderscode as integer) as boarders_code,
        try_cast(OfficialSixthFormcode as integer) as official_sixth_form_code,
        try_cast(Gendercode as integer) as gender_code,
        try_cast(ReligiousCharactercode as integer) as religious_character_code,
        try_cast(AdmissionsPolicycode as integer) as admissions_policy_code,
        try_cast(SchoolCapacity as integer) as school_capacity,
        try_cast(SpecialClassescode as integer) as special_classes_code,
        try_cast(NumberOfPupils as integer) as number_of_pupils,
        try_cast(NumberOfBoys as integer) as number_of_boys,
        try_cast(NumberOfGirls as integer) as number_of_girls,
        try_cast(TrustSchoolFlagcode as integer) as trust_school_flag_code,
        try_cast(Trustscode as integer) as trusts_code,
        try_cast(Federationscode as integer) as federations_code,
        try_cast(UKPRN as integer) as ukprn,
        try_cast(FEHEIdentifier as integer) as fehe_identifier,
        try_cast(TeenMothPlaces as integer) as teen_moth_places,
        try_cast(PlacesPRU as integer) as places_pru,
        try_cast(ResourcedProvisionOnRoll as integer) as resourced_provision_on_roll,
        try_cast(ResourcedProvisionCapacity as integer) as resourced_provision_capacity,
        try_cast(SenUnitOnRoll as integer) as sen_unit_on_roll,
        try_cast(SenUnitCapacity as integer) as sen_unit_capacity,
        try_cast(Easting as integer) as easting,
        try_cast(Northing as integer) as northing,
        try_cast(SENStat as integer) as sen_stat,
        try_cast(SENNoStat as integer) as sen_no_stat,
        try_cast(PreviousLAcode as integer) as previous_la_code,
        try_cast(PreviousEstablishmentNumber as integer) as previous_establishment_number,
        try_cast(TelephoneNum as bigint) as telephone_num,
        try_cast(UPRN as bigint) as uprn,
        try_cast(PercentageFSM as double) as percentage_fsm,
        --dates
        try_cast(OpenDate as date) as open_date,
        try_cast(CloseDate as date) as close_date,
        try_cast(CensusDate as date) as census_date,
        try_cast(LastChangedDate as date) as last_changed_date,
        try_cast(DateOfLastInspectionVisit as date) as date_of_last_inspection_visit,
        try_cast(NextInspectionVisit as date) as next_inspection_visit,
        --strings
        nullif(trim(LAname), '') as la_name,
        nullif(trim(EstablishmentName), '') as establishment_name,
        nullif(trim(TypeOfEstablishmentname), '') as type_of_establishment_name,
        nullif(trim(EstablishmentTypeGroupname), '') as establishment_type_group_name,
        nullif(trim(EstablishmentStatusname), '') as establishment_status_name,
        nullif(trim(ReasonEstablishmentOpenedname), '') as reason_establishment_opened_name,
        nullif(trim(ReasonEstablishmentClosedname), '') as reason_establishment_closed_name,
        nullif(trim(PhaseOfEducationname), '') as phase_of_education_name,
        nullif(trim(Boardersname), '') as boarders_name,
        nullif(trim(NurseryProvisionname), '') as nursery_provision_name,
        nullif(trim(OfficialSixthFormname), '') as official_sixth_form_name,
        nullif(trim(Gendername), '') as gender_name,
        nullif(trim(ReligiousCharactername), '') as religious_character_name,
        nullif(trim(ReligiousEthosname), '') as religious_ethos_name,
        nullif(trim(Diocesecode), '') as diocese_code,
        nullif(trim(Diocesename), '') as diocese_name,
        nullif(trim(AdmissionsPolicyname), '') as admissions_policy_name,
        nullif(trim(SpecialClassesname), '') as special_classes_name,
        nullif(trim(TrustSchoolFlagname), '') as trust_school_flag_name,
        nullif(trim(Trustsname), '') as trusts_name,
        nullif(trim(SchoolSponsorFlagname), '') as school_sponsor_flag_name,
        nullif(trim(SchoolSponsorsname), '') as school_sponsors_name,
        nullif(trim(FederationFlagname), '') as federation_flag_name,
        nullif(trim(Federationsname), '') as federations_name,
        nullif(trim(FurtherEducationTypename), '') as further_education_type_name,
        nullif(trim(OfstedLastInsp), '') as ofsted_last_insp,
        nullif(trim(OfstedSpecialMeasurescode), '') as ofsted_special_measures_code,
        nullif(trim(OfstedSpecialMeasuresname), '') as ofsted_special_measures_name,
        nullif(trim(Street), '') as street,
        nullif(trim(Locality), '') as locality,
        nullif(trim(Address3), '') as address3,
        nullif(trim(Town), '') as town,
        nullif(trim(Countyname), '') as county_name,
        nullif(trim(Postcode), '') as postcode,
        nullif(trim(SchoolWebsite), '') as school_website,
        nullif(trim(HeadTitlename), '') as head_title_name,
        nullif(trim(HeadFirstName), '') as head_first_name,
        nullif(trim(HeadLastName), '') as head_last_name,
        nullif(trim(HeadPreferredJobTitle), '') as head_preferred_job_title,
        nullif(trim(BSOInspectorateNamename), '') as bso_inspectorate_name_name,
        nullif(trim(InspectorateReport), '') as inspectorate_report,
        nullif(trim(TeenMothname), '') as teen_moth_name,
        nullif(trim(CCFname), '') as ccf_name,
        nullif(trim(SENPRUname), '') as sen_pru_name,
        nullif(trim(EBDname), '') as ebd_name,
        nullif(trim(FTProvname), '') as ft_prov_name,
        nullif(trim(EdByOthername), '') as ed_by_other_name,
        nullif(trim(Section41Approvedname), '') as section41_approved_name,
        nullif(trim(SEN1name), '') as sen1_name,
        nullif(trim(SEN2name), '') as sen2_name,
        nullif(trim(SEN3name), '') as sen3_name,
        nullif(trim(SEN4name), '') as sen4_name,
        nullif(trim(SEN5name), '') as sen5_name,
        nullif(trim(SEN6name), '') as sen6_name,
        nullif(trim(SEN7name), '') as sen7_name,
        nullif(trim(SEN8name), '') as sen8_name,
        nullif(trim(SEN9name), '') as sen9_name,
        nullif(trim(SEN10name), '') as sen10_name,
        nullif(trim(SEN11name), '') as sen11_name,
        nullif(trim(SEN12name), '') as sen12_name,
        nullif(trim(SEN13name), '') as sen13_name,
        nullif(trim(TypeOfResourcedProvisionname), '') as type_of_resourced_provision_name,
        nullif(trim(GORcode), '') as gor_code,
        nullif(trim(GORname), '') as gor_name,
        nullif(trim(DistrictAdministrativecode), '') as district_administrative_code,
        nullif(trim(DistrictAdministrativename), '') as district_administrative_name,
        nullif(trim(AdministrativeWardcode), '') as administrative_ward_code,
        nullif(trim(AdministrativeWardname), '') as administrative_ward_name,
        nullif(trim(ParliamentaryConstituencycode), '') as parliamentary_constituency_code,
        nullif(trim(ParliamentaryConstituencyname), '') as parliamentary_constituency_name,
        nullif(trim(UrbanRuralcode), '') as urban_rural_code,
        nullif(trim(UrbanRuralname), '') as urban_rural_name,
        nullif(trim(GSSLACodename), '') as gss_la_code_name,
        nullif(trim('census_area_statistic_ward_code'), '') as census_area_statistic_ward_code,
        nullif(trim(MSOAname), '') as msoa_name,
        nullif(trim(LSOAname), '') as lsoa_name,
        nullif(trim(InspectorateNamename), '') as inspectorate_name_name,
        nullif(trim(BoardingEstablishmentname), '') as boarding_establishment_name,
        nullif(trim(PropsName), '') as props_name,
        nullif(trim(PreviousLAname), '') as previous_la_name,
        nullif(trim(OfstedRatingname), '') as ofsted_rating_name,
        nullif(trim(RSCRegionname), '') as rsc_region_name,
        nullif(trim(Countryname), '') as country_name,
        nullif(trim(SiteName), '') as site_name,
        nullif(trim(MSOAcode), '') as msoa_code,
        nullif(trim(LSOAcode), '') as lsoa_code

    from raw_csv

)

select * from stg_gias